---
title: "shippping random walk"
# subtitle: ""
# bibliography: linen_quality.bib
format: 
  html:
    mainfont: Quattrocento Sans
    sansfont: Cinzel
    toc: true
    toc-location: left
    toc-depth: 3
    fig-cap-location: margin
execute: 
  echo: false
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

```{r}
#| include: false

library(tidyverse)
library(ggtext)
library(here)
library(rstan)

here::i_am("ship_random_walk.qmd")

# stan options
util <- new.env()
rstan_options(auto_write = TRUE)
source(here("mcmc_analysis_tools_rstan.R"), local = util)
source(here("mcmc_visualization_tools.R"), local = util)

# graphics options
extrafont::font_import(pattern = "QuattrocentoSans", prompt = FALSE)
extrafont::loadfonts(device = "win")
ggplot2::theme_set(theme_minimal() +
                     theme(text = element_text(size = 15,
                                               family = "Quattrocento Sans"),
                           margins = margin(10, 15, 25, 15),
                           axis.title.x = element_text(vjust = -3),
                           axis.title.y = element_text(vjust =  3)))
options(knitr.table.html.attr = "quarto-disable-processing=true")

# inline content
inline <- list()
```

```{r}
c_light <- c("#D6EBEA")
c_light_highlight <- c("#B5DBD9")
c_mid <- c("#92CAC6")
c_mid_highlight <- c("#5FB2AC")
c_dark <- c("#369F97")
c_dark_highlight <- c("#00867B")

c_dark_trans <- c("#005D5580")
c_purple_trans <- c("#D400C380")

c_list <- list(c_light, c_light_highlight, c_mid, 
                 c_mid_highlight, c_dark, c_dark_highlight)
```

# data

```{r}
ex_data <- 
  tibble(
    relic = 1:75
  ) %>%
  mutate(prod_error = rnorm(n = n(), mean = 0.6, sd = 1),
         prod = cumsum(prod_error),
         ship_error = rexp(n = n(), rate = 1/2),
         deliv = prod + ship_error,
         is_observed = row_number() %in% sample(1:50, size = 25, replace = FALSE))

ex_data %>%
  ggplot(aes(x = relic)) +
  geom_point(aes(y = deliv, color = is_observed)) +
  scale_color_manual(guide = "none",
                     values = c("TRUE"= "#000000", "FALSE" = "#CCCCCC"))
```

::: {.callout-important}
write observational model down
:::

# prior predictive

```{r}
writeLines(readLines(here("stan_programs/ship_random_walk_bayesian_ensemble.stan")))
```

```{r}
fit_ensemble <- stan(
  file = here("stan_programs/ship_random_walk_bayesian_ensemble.stan"),
  data = list(N = nrow(ex_data)),
  iter = 5000, chains = 2,
  warmup = 0, algorithm = "Fixed_param",
  refresh = 1000
)
```

```{r}
# idx <- rep(1:nrow(ex_data), each = 2)
# x <- sapply(X = 1:length(idx), 
#             FUN = \(b){if(b %% 2 == 0) {idx[b] + 0.5} else {idx[b] - 0.5}})
# cred <- sapply(1:nrow(ex_data), \(i){quantile(extract(fit_ensemble)$y[ , i], probs = seq(0.1, 0.9, by = 0.1))})

plot(1, type = "n", 
     xlim = c(1, 75), ylim = range(extract(fit_ensemble)$production[1:20, ]),
     xlab = "y", main = "Prior Predictive")
# for (i in 1:((nrow(cred) - 1)/2)) {
#   polygon(x = c(x, rev(x)),
#           y = c(rep(cred[i, ], each = 2), 
#                 rep(rev(cred[nrow(cred) - i + 1, ]), each = 2)),
#           col = c_list[[i]], border = NA)
# }
# lines(x, rep(cred[5, ], each = 2), 
#       col = c_dark, lwd = 3)
for (i in 1:20) {
  lines(x = 1:75,
        y = extract(fit_ensemble)$production[i, ],
        col = c_dark_trans, lwd = 2)
}

plot(1, type = "n", 
     xlim = c(1, 75), ylim = range(extract(fit_ensemble)$production[1:20, ]),
     xlab = "y", main = "Prior Predictive")
lines(x = 1:75,
      y = extract(fit_ensemble)$production[1, ],
      col = c_dark_trans, lwd = 2)
points(x = 1:75,
       y = extract(fit_ensemble)$delivery[1, ],
       col = c_dark_trans, pch = 19)
```

# posterior retrodictive

```{r}
writeLines(readLines(here("stan_programs/ship_random_walk.stan")))
```

```{r}
stan_data <- list(
  N = nrow(ex_data),
  N_obs = sum(ex_data$is_observed),
  relic_obs = ex_data$relic[ex_data$is_observed],
  relic_unobs = ex_data$relic[!ex_data$is_observed],
  delivery_obs = ex_data$deliv[ex_data$is_observed]
)

fit <- stan(
  file = here("stan_programs/ship_random_walk.stan"),
  data = stan_data,
  iter = 5000, chains = 4, cores = 4, refresh = 1000
)
```

```{r}
hist(extract(fit)$prod_mu)
hist(extract(fit)$prod_sigma)
hist(extract(fit)$ship_sigma)
hist(extract(fit)$ship_lambda)

as_tibble(extract(fit)) %>%
  select(starts_with(c("prod_", "ship_"))) %>%
  mutate(across(.cols = everything(),
                .fns  = log)) %>%
  pairs()

# prior contraction
# <go do betancourt's contraction thing>
```

```{r}
idx <- rep(1:stan_data$N, each = 2)
x <- sapply(X = 1:length(idx), 
            FUN = \(b){if(b %% 2 == 0) {idx[b] + 0.5} else {idx[b] - 0.5}})
cred <- sapply(1:stan_data$N, \(i){quantile(extract(fit)$production[ , i], probs = seq(0.1, 0.9, by = 0.1))})

plot(1, type = "n", 
     xlim = range(x), ylim = range(cred),
     xlab = "y", main = "Posterior Retrodictive")
for (i in 1:((nrow(cred) - 1)/2)) {
  polygon(x = c(x, rev(x)),
          y = c(rep(cred[i, ], each = 2), 
                rep(rev(cred[nrow(cred) - i + 1, ]), each = 2)),
          col = c_list[[i]], border = NA)
}
lines(x, rep(cred[5, ], each = 2), 
      col = c_dark, lwd = 1)
points(x = stan_data$relic_obs, y = stan_data$delivery,
       col = c_purple_trans, pch = 19)
# lines(x, rep(stan_data$y, each = 2), 
#       col = c_purple_trans, lwd = 3)
```

there's no latent measurement here like for rounding error so no more interesting summaries (i don't think?)

# Dune

use it on dune

```{r}
delivery_raw <- read_csv(here("data/raw/delivery_data.csv"))

dune <- 
  delivery_raw %>%
  filter(game == "Dune", 
         !is.na(relic),
         !is.na(delivered),
         !(relic %in% c(756, 711, 624))) %>%
  mutate(delivered = as.integer(delivered - as.Date("2025-04-14"))) %>%
  arrange(relic)
```

```{r}
# trying it with truncated real data
stan_data_dune <- list(
  N = 720 - 500,
  N_obs = nrow(dune[dune$relic >= 500, ]),
  relic_obs = dune$relic[dune$relic >= 500] - 500,
  relic_unobs = setdiff(1:(720 - 500), dune$relic[dune$relic >= 500] - 500),
  delivery_obs = dune$delivered[dune$relic >= 500] - 335
)

fit_dune <- stan(
  file = here("stan_programs/ship_random_walk.stan"),
  data = stan_data_dune,
  iter = 2000, chains = 1, cores = 1, refresh = 1000
)
```

something's really wrong, are the chains not mixing?

```{r}
hist(extract(fit_dune)$prod_mu)
hist(extract(fit_dune)$prod_sigma)
hist(extract(fit_dune)$ship_sigma)
hist(extract(fit_dune)$ship_lambda)

as_tibble(extract(fit_dune)) %>%
  # sample_n(5000) %>%
  select(starts_with(c("prod_", "ship_"))) %>%
  mutate(across(.cols = everything(),
                .fns  = log)) %>%
  pairs()
```

```{r}
idx <- rep(1:stan_data_dune$N, each = 2)
x <- sapply(X = 1:length(idx), 
            FUN = \(b){if(b %% 2 == 0) {idx[b] + 0.5} else {idx[b] - 0.5}})
cred <- sapply(1:stan_data_dune$N, \(i){quantile(extract(fit_dune)$production[ , i], probs = seq(0.1, 0.9, by = 0.1))})

plot(x = 1, type = "n", 
     xlim = range(x), 
     ylim = range(cred),
     # ylim = c(min(cred, stan_data_dune$delivery_obs),
     #          max(cred, stan_data_dune$delivery_obs)),
     xlab = "y", main = "Posterior Retrodictive")
for (i in 1:((nrow(cred) - 1)/2)) {
  polygon(x = c(x, rev(x)),
          y = c(rep(cred[i, ], each = 2), 
                rep(rev(cred[nrow(cred) - i + 1, ]), each = 2)),
          col = c_list[[i]], border = NA)
}
lines(x, rep(cred[5, ], each = 2), 
      col = c_dark, lwd = 1)
points(x = stan_data_dune$relic_obs, 
       y = stan_data_dune$delivery,
       col = c_purple_trans, pch = 19)

plot(x = 1, type = "n", 
     xlim = c(0, max(stan_data_dune$relic_obs)),
     ylim = c(0, max(stan_data_dune$delivery)))
points(x = stan_data_dune$relic_obs, 
       y = stan_data_dune$delivery,
       col = c_purple_trans, pch = 19)
```